PROJEKTCRM/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from django.urls import path, include
from leads.views import landing_page, LandingPageView, SignupView, DashboardView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('leads/',  include('leads.urls', namespace="leads")),
    path('agents/',  include('agents.urls', namespace="agents")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/urls.py
from django.urls import path
from .views import (
    AgentListView, AgentCreateView, AgentDetailView, 
     AgentUpdateView, AgentDeleteView
)

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    
]

leads/urls.py
from django.urls import path
from .views import (
    LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView,
    AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView,
    CategoryCreateView, CategoryUpdateView, CategoryDeleteView, LeadJsonView, 
    FollowUpCreateView, FollowUpUpdateView, FollowUpDeleteView
)

app_name = "leads"

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('json/', LeadJsonView.as_view(), name='lead-list-json'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(), name='assign-agent'),
    path('<int:pk>/category/', LeadCategoryUpdateView.as_view(), name='lead-category-update'),
    path('<int:pk>/followups/create/', FollowUpCreateView.as_view(), name='lead-followup-create'),
    path('followups/<int:pk>/', FollowUpUpdateView.as_view(), name='lead-followup-update'),
    path('followups/<int:pk>/delete/', FollowUpDeleteView.as_view(), name='lead-followup-delete'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('categories/', CategoryListView.as_view(), name='category-list'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),
    path('categories/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('categories/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),
    path('create-category/', CategoryCreateView.as_view(), name='category-create'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROJEKT CRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class="max-w-7xl mx-auto">
        {% include 'navbar.html' %}
        {% include 'messages.html' %}
        {% block content %}
        {% endblock content %}
    </div>
    {% include "scripts.html" %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM Dashboard
        </h1>
    
        <div class="flex flex-wrap -m-4 text-center">
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
                    <path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"></path>
                    <circle cx="9" cy="7" r="4"></circle>
                    <path d="M23 21v-2a4 4 0 00-3-3.87m-4-12a4 4 0 010 7.75"></path>
                </svg>
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_lead_count }}</h2>
                <p class="leading-relaxed">Total Leads</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ total_in_past30 }}</h2>
                <p class="leading-relaxed">Leads added in last 30 days</p>
                </div>
            </div>
            <div class="p-4 md:w-1/3 sm:w-1/2 w-full">
                <div class="border-2 border-gray-200 px-4 py-6 rounded-lg">
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="text-indigo-500 w-12 h-12 mb-3 inline-block" viewBox="0 0 24 24">
              <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
              <path d="M22 4L12 14.01l-3-3"></path>
            </svg>
                <h2 class="title-font font-medium text-3xl text-gray-900">{{ converted_in_past30 }}</h2>
                <p class="leading-relaxed">Converted in last 30 days</p>
                </div>
            </div>
        </div>
        
      </div>
    </div>
</section>
{% endblock content %}

templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="text-gray-700 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/crm.jpg' %}">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
            CRM built with Django
        </h1>
        <p class="mb-8 leading-relaxed">
            This CRM helps you manage your leads.
        </p>
        <div class="flex justify-center">
          <a href="{% url 'login' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
            Login to get started
          </a>
        </div>
      </div>
    </div>
</section>
{% endblock content %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="p-4 border-l-4
        {% if message.tags == 'success' %}
        bg-green-50 border-green-400
        {% elif message.tags == 'info' %}
        bg-blue-50 border-blue-400
        {% elif message.tags == 'warning' %}
        bg-yellow-50 border-yellow-400
        {% else %}
        bg-red-50 border-red-400
        {% endif %}
        ">
            <p class="text-sm
            {% if message.tags == 'success' %}
            text-green-700
            {% elif message.tags == 'info' %}
            text-blue-700
            {% elif message.tags == 'warning' %}
            text-yellow-700
            {% else %}
            text-red-700
            {% endif %}
            ">
                {{ message }}
            </p>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<header class="text-gray-700 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a href="{% url 'dashboard' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<g>
	<g>
		<path d="M478.33,68.409H33.67C15.105,68.409,0,83.514,0,102.079v307.841c0,18.566,15.105,33.67,33.67,33.67h444.66
			c18.566,0,33.67-15.105,33.67-33.67V102.079C512,83.514,496.895,68.409,478.33,68.409z M119.716,427.557H33.67
			c-9.725,0-17.637-7.912-17.637-17.637V102.079c0-9.725,7.912-17.637,17.637-17.637h86.046V427.557z M495.967,409.921
			c0,9.725-7.912,17.637-17.637,17.637h-342.58V84.443h342.58c9.725,0,17.637,7.912,17.637,17.637V409.921z"/>
	</g>
</g>
<g>
	<g>
		<path d="M196.142,102.614h-34.205c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h34.205
			c4.427,0,8.017-3.589,8.017-8.017S200.569,102.614,196.142,102.614z"/>
	</g>
</g>
<g>
	<g>
		<path d="M93.528,102.614H42.221c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h51.307
			c4.427,0,8.017-3.589,8.017-8.017S97.956,102.614,93.528,102.614z"/>
	</g>
</g>
<g>
	<g>
		<path d="M93.528,188.125H42.221c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h51.307
			c4.427,0,8.017-3.589,8.017-8.017S97.956,188.125,93.528,188.125z"/>
	</g>
</g>
<g>
	<g>
		<path d="M93.528,256.534H42.221c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h51.307
			c4.427,0,8.017-3.589,8.017-8.017S97.956,256.534,93.528,256.534z"/>
	</g>
</g>
<g>
	<g>
		<path d="M93.528,324.944H42.221c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h51.307
			c4.427,0,8.017-3.589,8.017-8.017S97.956,324.944,93.528,324.944z"/>
	</g>
</g>
<g>
	<g>
		<path d="M93.528,222.33H42.221c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h51.307c4.427,0,8.017-3.589,8.017-8.017
			S97.956,222.33,93.528,222.33z"/>
	</g>
</g>
<g>
	<g>
		<path d="M93.528,290.739H42.221c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h51.307
			c4.427,0,8.017-3.589,8.017-8.017S97.956,290.739,93.528,290.739z"/>
	</g>
</g>
<g>
	<g>
		<path d="M76.426,376.251H42.221c-4.427,0-8.017,3.589-8.017,8.017c0,4.427,3.589,8.017,8.017,8.017h34.205
			c4.427,0,8.017-3.589,8.017-8.017C84.443,379.84,80.853,376.251,76.426,376.251z"/>
	</g>
</g>
<g>
	<g>
		<path d="M76.426,136.818H42.221c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h34.205
			c4.427,0,8.017-3.589,8.017-8.017S80.853,136.818,76.426,136.818z"/>
	</g>
</g>
<g>
	<g>
		<path d="M264.551,102.614h-34.205c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h34.205
			c4.427,0,8.017-3.589,8.017-8.017S268.979,102.614,264.551,102.614z"/>
	</g>
</g>
<g>
	<g>
		<path d="M332.96,102.614h-34.205c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h34.205
			c4.427,0,8.017-3.589,8.017-8.017S337.388,102.614,332.96,102.614z"/>
	</g>
</g>
<g>
	<g>
		<path d="M401.37,102.614h-34.205c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h34.205
			c4.427,0,8.017-3.589,8.017-8.017S405.797,102.614,401.37,102.614z"/>
	</g>
</g>
<g>
	<g>
		<path d="M469.779,102.614h-34.205c-4.427,0-8.017,3.589-8.017,8.017s3.589,8.017,8.017,8.017h34.205
			c4.427,0,8.017-3.589,8.017-8.017S474.206,102.614,469.779,102.614z"/>
	</g>
</g>
<g>
	<g>
		<path d="M252.266,283.797c-3.54-2.659-8.566-1.945-11.224,1.595c-6.636,8.833-16.768,13.899-27.798,13.899
			c-19.155,0-34.739-15.584-34.739-34.739s15.584-34.739,34.739-34.739c11.038,0,21.176,5.073,27.81,13.917
			c2.657,3.541,7.682,4.26,11.223,1.602s4.258-7.682,1.602-11.223c-9.693-12.92-24.503-20.329-40.636-20.329
			c-27.995,0-50.772,22.777-50.772,50.772s22.777,50.772,50.772,50.772c16.12,0,30.924-7.4,40.617-20.303
			C256.521,291.481,255.807,286.456,252.266,283.797z"/>
	</g>
</g>
<g>
	<g>
		<path d="M331.35,280.396c15.247-3.209,26.73-16.76,26.73-32.948c0-18.566-15.105-33.67-33.67-33.67h-42.756
			c-4.427,0-8.017,3.589-8.017,8.017v85.511c0,4.427,3.589,8.017,8.017,8.017s8.017-3.589,8.017-8.017v-26.188h22.18l23.248,30.998
			c1.576,2.1,3.983,3.207,6.42,3.207c1.674,0,3.362-0.523,4.804-1.603c3.541-2.656,4.26-7.682,1.603-11.223L331.35,280.396z
			 M289.67,265.086v-35.273h34.739c9.725,0,17.637,7.912,17.637,17.637s-7.912,17.637-17.637,17.637H289.67z"/>
	</g>
</g>
<g>
	<g>
		<path d="M469.205,306.508l-8.551-85.51c-0.368-3.675-3.198-6.623-6.855-7.14c-3.653-0.518-7.194,1.531-8.565,4.961l-26.762,66.903
			l-26.762-66.903c-1.372-3.429-4.908-5.474-8.565-4.961c-3.657,0.517-6.487,3.465-6.855,7.14l-8.551,85.511
			c-0.44,4.406,2.774,8.334,7.18,8.775c4.401,0.44,8.333-2.774,8.775-7.18l5.293-52.927l22.043,55.107
			c1.218,3.043,4.164,5.039,7.443,5.039s6.226-1.996,7.443-5.039l22.043-55.107l5.293,52.927c0.414,4.134,3.898,7.219,7.968,7.219
			c0.267,0,0.536-0.013,0.807-0.041C466.431,314.843,469.645,310.914,469.205,306.508z"/>
	</g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
<g>
</g>
</svg>
        <span class="ml-3 text-xl">PROJEKT CRM</span>
        
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% if not request.user.is_authenticated %}
          <a href="{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>
        {% else %}
          {% if request.user.is_organisor %}
          <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a>
          {% endif %}
          <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a>
          <a href="{% url 'leads:category-list' %}" class="mr-5 hover:text-gray-900">Categories</a>
          <a href="{% url 'dashboard' %}" class="mr-5 hover:text-gray-900">Dashboard</a>
        {% endif %}
      </nav>
      {% if request.user.is_authenticated %}
        Logged in as: {{ request.user.username }}
        <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
          Logout
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
            </svg>
        </a>
      {% else %}
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-200 border-0 py-1 px-3 focus:outline-none hover:bg-gray-300 rounded text-base mt-4 md:mt-0">
          Login
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
              <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
      </a>
      {% endif %}
    </div>
</header>

templates/scripts.html
{% load static %}
<script srct="{% static 'js/main.js' %}">
</script>